version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - rest-server
    networks:
      - frontend

  rest-server:
    build: ./rest-server
    ports:
      - "8080:8080"
    depends_on:
      - db-server
    networks:
      - frontend
      - backend

  db-server:
    build: ./db-server
    ports:
      - "8081:8081"
    volumes:
      - db-data:/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: