# filepath: build-ops/docker-compose.yml
version: '3.8'

services:
  app:
    container_name: spring-boot-rest-api
    build:
      context: ..
      dockerfile: build-ops/Dockerfile
    image: ai-io-x-devops:latest
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
    # docker-compose build
    # docker-compose run app
    # Command to start a bash shell for manual commands
    # command: bash
    # Command to run Maven tests
    # command: mvn clean test
    # Command to run the application
    # docker-compose up --build
    command: java -jar app.jar